import enum
from datetime import datetime

from argon2 import PasswordHasher
from argon2.exceptions import Argon2Error
from database import Base
from database import Base
from sqlalchemy import TIMESTAMP, func, ForeignKey, String
from sqlalchemy.ext.asyncio import AsyncAttrs
from sqlalchemy.ext.hybrid import hybrid_property, hybrid_method
from sqlalchemy.orm import Mapped, mapped_column

_hasher = PasswordHasher()

__all__ = ["Base", "User", "UserLock",
           "ResponseType", "GrantType", "OAuth2Client", "OAuth2Code", "OAuth2DeviceCode", "OAuth2AccessRevoked",
           "OAuth2ProviderSession", "OAuth2UserSession", "OAuth2ClientSession"
           ]


# -*- Common definitions -*-

class AMR(enum.Enum):
    """
    Authentication Method Reference
    """
    # -*- Based on biometric -*-
    face = "face"
    """
    Facial recognition.
    [RFC8176, Section 2]
    
    Type of biometric authentication by face recognition via special software (may use special hardware).
    """
    fpt = "fpt"
    """
    Fingerprint biometric.
    [RFC8176, Section 2]
    
    Type of biometric authentication by fingerprint via special hardware.
    """
    iris = "iris"
    """
    Iris scan biometric.
    [RFC8176, Section 2]
    
    Type of biometric authentication by iris scan via special hardware.
    """
    retina = "retina"
    """
    Retina scan biometric.
    [RFC8176, Section 2]
    
    Type of biometric authentication by retina scan via special hardware.
    """
    vbm = "vbm"
    """
    Voice biometric.
    [RFC8176, Section 2]
    
    Type of biometric authentication by retina scan via special software.
    """
    # -*- Based on secret -*-
    pwd = "pwd"
    """
    Password-based authentication.
    [RFC8176, Section 2]
    """
    pin = "pin"
    """
    Personal Identification Number or pattern.
    [RFC8176, Section 2]
    """
    sc = "sc"
    """
    Smart card.
    [RFC8176, Section 2]
    """
    # -*- Based on temp secret generated by user or delivered to user via different channel ('tel', 'sms', etc.) -*-
    otp = "otp"
    """
    One-time password.
    [RFC8176, Section 2]
    """
    sms = "sms"
    """
    Confirmation using SMS.
    [RFC8176, Section 2]
    """
    tel = "tel"
    """
    Confirmation by telephone call.
    [RFC8176, Section 2]
    """
    # -*- Status marks -*-
    # -*- Proof-of-possession of key marks:
    # -*- End-User use as primary or secondary method that involve software or hardware key (not password or similar) -*-
    pop = "pop"
    """
    Proof-of-possession of a key.
    [OpenID Connect Extended Authentication Profile (EAP) ACR Values 1.0]
    """
    swk = "swk"
    """
    Proof-of-possession of a software-secured key.
    [RFC8176, Section 2]
    """
    hwk = "hwk"
    """
    Proof-of-possession of a hardware-secured key.
    [RFC8176, Section 2]
    """
    # -*- User geo information mark: -*-
    # -*- User geolocation information (from ip address or GPS) involved in authentification process -*-
    geo = "geo"
    """
    Geolocation.
    [RFC8176, Section 2]
    """
    # -*- User knowledge mark: -*-
    # -*- User specific knowledge (may not secure) involved in authentification process -*-
    kba = "kba"
    """
    Knowledge-based authentication.
    [RFC8176, Section 2]
    """
    # -*- User presence mark: -*-
    # -*- User presence test involved in authentication process -*-
    user = "user"
    """
    User presence test.
    [RFC8176, Section 2]
    """
    # -*- Risk-based model mark: -*-
    # -*- Used risk-based authentication model: additional authentication methods required if necessary. -*-
    rba = "rba"
    """
    Risk-based authentication.
    [RFC8176, Section 2]
    """
    # -*- Multi-channel mark: -*-
    # -*- For authentication process at the moment used several communication channels. -*-
    mca = "mca"
    """
    Multiple-channel authentication.
    [RFC8176, Section 2]
    """
    # -*- Multi-factor mark: -*-
    # -*- For authentification process at the moment used several authentication methods. -*-
    mfa = "mfa"
    """
    Multiple-factor authentication.
    [RFC8176, Section 2]
    """
    # -*- Windows OS integrated methods mark: -*-
    # -*- Specific Windows OS integrated authentication methods involved in authentication process -*-
    wia = "wia"
    """
    Windows integrated authentication.
    [RFC8176, Section 2]
    """


class ResponseType(enum.Enum):
    Code = "code"
    Token = "token"
    IDToken = "id_token"
    IDTokenToken = "id_token token"
    CodeToken = "code token"
    CodeIDToken = "code id_token"
    CodeIDTokenToken = "code id_token token"
    TypeNone = "none"

    def __str__(self):
        return self.value


class GrantType(enum.Enum):
    """
    Grand type 'refresh_token' not specified in this enum because its allowed automatically if refresh token emitted.
    """
    AuthorizationCode = "authorization_code"
    Implicit = "implicit"
    Password = "password"
    ClientCredentials = "client_credentials"
    DeviceCode = "urn:ietf:params:oauth:grant-type:device_code"

    def __str__(self):
        return self.value


# -*- User definitions -*-

class User(AsyncAttrs, Base):
    """
    OAuth2 User is basic user data representation.
    It's include:
        login -- identifier username from small subset of allowed chars (a-zA-Z0-9_-) and some simple rules
            It's used as human-readable alternative inner user id
            This value by default used for login process
        email -- primary email address can be verified or non-verified
            If it verified (verification process lies outside the scope of this library) can be used as login
            Also this value will be returned in id_token and userinfo if requested
            (you can store additional emails, but they will not be used by this library)
        phone -- phone number can be verified or non-verified
            If it verified (verification process lies outside the scope of this library) can be used as login
            Also this value will be returned in id_token and userinfo if requested
            (you can store additional phone numbers, but they will not be used by this library)
        scope -- user scopes (access rules)
            This library define some specific values for this work and some values defined by openid connect
            You can use you're own scope values in app logic
        active -- status of activation of account
            When active is False, user can login to provider, but:
                - He can't authorize third-party clients
                - He can't interact with transparent apps (only provider frontend allowed)
                - He can't interact any resource servers
                - He can only resieve userinfo from /userinfo endpoint
            This state of user created for:
                - User can see that it's account present in system (can see user profile page),
                    but wait when verification process completed
                    (Some users being confused when they registered on site and can not login to it)
    """
    __tablename__ = "oauth2_user"
    id: Mapped[int] = mapped_column(primary_key=True)
    # Unique alphanumeric user identification (aka username)
    login: Mapped[str] = mapped_column(nullable=False, unique=True, index=True)
    # Primary email. Can be used as login for authentification
    # Returned as userinfo email field
    email: Mapped[str] = mapped_column(nullable=True, unique=True, index=True)
    email_verified: Mapped[bool] = mapped_column(nullable=False, server_default="FALSE")
    # Primary phone number. Can be used as login for authentification
    # Returned as userinfo phone_number field
    phone: Mapped[str] = mapped_column(nullable=True, unique=True, index=True)
    phone_verified: Mapped[bool] = mapped_column(nullable=False, server_default="FALSE")
    # User space-delimited scope (his rights)
    scope: Mapped[str] = mapped_column(nullable=False)
    # External authenticated users can haven't password
    _password: Mapped[str] = mapped_column("password", nullable=True)
    # Inactive account can success login in provider but can't interact with system
    # Frontend can display user home page.
    active: Mapped[bool] = mapped_column(nullable=False, server_default="FALSE")

    created_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False,
                                                 server_default=func.current_timestamp())
    password_changed_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False,
                                                          server_default=func.current_timestamp())
    # Last time primary email or phone updated
    updated_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False,
                                                 server_default=func.current_timestamp())

    @hybrid_property
    def password(self):
        return ""

    @password.setter
    def password(self, value: str):
        self._password = _hasher.hash(value)

    @hybrid_property
    def scopes(self):
        return self.scope.split()

    @scopes.setter
    def scopes(self, value: list[str]):
        self.scope = " ".join(value)

    @hybrid_method
    def verify_password(self, value: str):
        try:
            _hasher.verify(self._password, value)
            if _hasher.check_needs_rehash(self._password):
                self._password = _hasher.hash(value)
            return True
        except Argon2Error:
            return False


class UserLock(AsyncAttrs, Base):
    """
    On this table login system locked per user login (for change simultaneous tries to linear for counters)
    """
    __tablename__ = 'oauth2_user_lock'
    id: Mapped[int] = mapped_column(ForeignKey("oauth2_user.id", ondelete="CASCADE"), primary_key=True)
    # LOGIN
    # list of allowed primary methods for End-User authentication. Default: pwd (password)
    login_via: Mapped[str] = mapped_column(nullable=False, server_default="pwd")
    # list of allowed external client_id via that login allowed.
    # Note: external login disable mfa and reauthenticate methods for session, these allowed only via same external.
    # Note: external login not allowed:
    #   - if End-User not enable this external method.
    #   - if End-User not exists in system (in this case registration flow will be started)
    login_via_external: Mapped[str] = mapped_column(nullable=False, server_default="")
    # login attempts count
    login_attempt_count: Mapped[int] = mapped_column(nullable=False, server_default="0")
    # Last login (for reset counter if last attempt will be very old)
    login_last_attempt_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=True)
    # MFA
    # Enabled mfa methods.
    # In this column specified additional methods, that will be performed to validate session.
    # session without completed mfa not allow any operations exclude mfa.
    # https://www.iana.org/assignments/authentication-method-reference-values/authentication-method-reference-values.xhtml
    # If you use alternative main authorization method (instead of password), don't add it to this column:
    # it's only for ADDITIONAL methods (after successful main method)
    # list of allowed secondary methods for End-User authentication. One of this must be completed.
    mfa_via: Mapped[str] = mapped_column(nullable=False, server_default="")
    # mfa attempts count
    mfa_attempt_count: Mapped[int] = mapped_column(nullable=False, server_default="0")
    # Last mfa (for reset counter if last attempt will be very old)
    mfa_last_attempt_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=True)
    # REAUTHENTICATE
    # Only for provider sessions
    # Process of reauthentication required confirmation via one of 'mfa_via' or 'login_via' method by default
    # If you want constraint allowed methods, set it in reauthenticate_via
    # Use this counter for reauthenticate process. (For separate this counter of login counter)
    # If you realize own reauthenticate method, call reauthenticate_callback with status for mark failed and successful reauthentication
    # reauthenticate attempts count
    reauthenticate_attempt_count: Mapped[int] = mapped_column(nullable=False, server_default="0")
    # Last reauthenticate (for reset counter if last attempt will be very old)
    reauthenticate_last_attempt_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=True)
    # BLOCK
    # User block status. If blocked, error returned when login will be tried.
    # If you realise custom main auth methods, don't forget check block status of user.
    block: Mapped[bool] = mapped_column(nullable=False, server_default="FALSE")
    block_reason: Mapped[str] = mapped_column(nullable=True)
    deleted: Mapped[bool] = mapped_column(nullable=False, server_default="FALSE")


class UserOTP(AsyncAttrs, Base):
    __tablename__ = 'oauth2_user_otp'
    id: Mapped[int] = mapped_column(ForeignKey("oauth2_user.id", ondelete="CASCADE"), primary_key=True)
    # User successful verify setup, if true 'otp' value added to 'mfa_via'
    # also into 'amr' of session will be added 'mfa otp'
    # ('mca' or 'mfa' values added into amr if several methods used:
    # 'mca' if this methods multichannel (password in browser + code from telephone call (or voice answer to call))
    # 'mfa' if this methods use one channel (password and otp code in browser).
    # basically, if )
    setup_complete: Mapped[bool] = mapped_column(nullable=False, server_default="FALSE")
    totp_secret: Mapped[str] = mapped_column(nullable=False)
    hotp_secret: Mapped[str] = mapped_column(nullable=False)
    hotp_init: Mapped[int] = mapped_column(nullable=False)
    hotp_codes: Mapped[str] = mapped_column(nullable=False)

    # @hybrid_property
    # def otp_codes(self) -> list[str] | None:
    #     if self._otp_codes is not None:
    #         return json.loads(self._otp_codes)
    #     return None
    #
    # @otp_codes.setter
    # def otp_codes(self, value: list[str] | None):
    #     if value is not None:
    #         self._otp_codes = json.dumps(value)
    #     else:
    #         self._otp_codes = None


# -*- Client definitions -*-

class OAuth2SectorIdentifier(AsyncAttrs, Base):
    """
    TODO: Add description here
    """
    __tablename__ = 'oauth2_sector_identifier'
    id: Mapped[int] = mapped_column(primary_key=True)
    # Basically hostname of client used for pairwise sub calculation
    # Used instead of extract hostname from redirect_uri
    # Initial value can be extracted once from registered redirect_uri
    sector: Mapped[str] = mapped_column(nullable=False, unique=True)
    sector_salt: Mapped[str] = mapped_column(nullable=False)


class OAuth2AZPIdentifier(AsyncAttrs, Base):
    """
    TODO: Add description here
    """
    __tablename__ = 'oauth2_azp_identifier'
    id: Mapped[int] = mapped_column(primary_key=True)
    azp: Mapped[str] = mapped_column(nullable=False, unique=True)


class OAuth2Client(AsyncAttrs, Base):
    __tablename__ = "oauth2_client"
    # Inner id for clients
    id: Mapped[int] = mapped_column(primary_key=True)
    # Display name of client for End-User
    display_name: Mapped[str] = mapped_column(nullable=False)
    # client_id as client login
    client_id: Mapped[int] = mapped_column(nullable=False, unique=True, index=True)
    # client_secret for confidential clients
    _client_secret: Mapped[str | None] = mapped_column("client_secret", nullable=True)
    # Enable or disable client
    enabled: Mapped[bool] = mapped_column(nullable=False, server_default="TRUE")
    # Confidential client or not
    confidential: Mapped[bool] = mapped_column(nullable=False, server_default="FALSE")
    # Client bound to user (local user client) (If users can register new clients)
    for_user_id: Mapped[int | None] = mapped_column(ForeignKey("oauth2_user.id", ondelete='CASCADE'),
                                                    nullable=True, index=True)
    # Semicolon-separated list of allowed response types (if grant type equals 'authorization_code' or 'implicit')
    _response_types: Mapped[str] = mapped_column("response_types", nullable=True)
    # Grant type enabled for this client (only one allowed, exclude refresh_token)
    grant_type: Mapped[GrantType] = mapped_column(String, nullable=False, server_default="authorization_code")
    # Enabled or disabled emitting refresh tokens. Note that some response types not allow refresh tokens at all
    emit_refresh_token: Mapped[bool] = mapped_column(nullable=False, server_default="TRUE")
    # Enabled or disabled rotating refresh tokens. refresh_token grant will discard old token and create new
    rotate_refresh_token: Mapped[bool] = mapped_column(nullable=False, server_default="TRUE")
    # Space-delimited default (and interpret as minimal) scope values (End-User must allow all of this)
    # If client explicit request less scopes that it's presented, explicit scope will be used
    scope: Mapped[str] = mapped_column(nullable=False, server_default="")
    # Space-delimited max scope values that this client can request
    # If client explicit request more scopes than max_scopes, provider may truncate scopes or reject request
    max_scope: Mapped[str] = mapped_column(nullable=True)
    # \n-separated list of registered redirect_uris for client (used only for 'authorization_code' and 'implicit')
    # If contains only one redirect_uri, it is interpreting as default value
    _redirect_uris: Mapped[str] = mapped_column(nullable=True)
    # Special client, if True grant_type must be 'password'
    # and 'scope', 'redirect_uris', 'for_user_id', lifetimes, 'reauthenticated_at' ignored (derived from frontend)
    # Client acts as user-agent (provider frontend)
    # Used as alternative variant for browser-based system applications.
    # Don't set this flag for third-party clients
    transparent: Mapped[bool] = mapped_column(nullable=False, server_default="FALSE")
    # Redefines timing
    # Lifetime of our access token in minutes. Must be smaller
    access_lifetime: Mapped[int] = mapped_column(nullable=True)
    # Lifetime of our refresh token in hours. Session live time
    refresh_lifetime: Mapped[int] = mapped_column(nullable=True)
    # Authentication max_age in seconds. Time after that required reauthentication for sensitive operations.
    auth_max_age: Mapped[int] = mapped_column(nullable=True)
    # Enable token bounds settings
    access_ip_bound: Mapped[bool] = mapped_column(nullable=False, server_default="FALSE")
    refresh_ip_bound: Mapped[bool] = mapped_column(nullable=False, server_default="FALSE")
    dpop_bound: Mapped[bool] = mapped_column(nullable=False, server_default="FALSE")
    # ID of sector for pairwise sub generation
    # (if not specified, 'public' sub will be used (user.id int value converted to str)
    pairwise_sector_id: Mapped[int] = mapped_column(ForeignKey("oauth2_sector_identifier.id"), nullable=True)
    # Authorized party id. ID describe group of logically bound clients (from the same owner for example)
    azp_id: Mapped[int] = mapped_column(ForeignKey("oauth2_azp_identifier.id"), nullable=True)
    # Enable userinfo settings
    userinfo_as_jwt: Mapped[bool] = mapped_column(nullable=False, server_default="FALSE")

    @hybrid_property
    def client_secret(self):
        return "" if self._client_secret is not None else None

    @client_secret.setter
    def client_secret(self, value: str):
        self._client_secret = _hasher.hash(value)

    @hybrid_property
    def scopes(self):
        return self.scope.split()

    @scopes.setter
    def scopes(self, value: list[str]):
        self.scope = " ".join(value)

    @hybrid_property
    def max_scopes(self):
        return self.max_scope.split()

    @max_scopes.setter
    def max_scopes(self, value: list[str]):
        self.max_scope = " ".join(value)

    @hybrid_property
    def response_types(self) -> list[ResponseType]:
        lst = self._response_types.split(";")
        return list(map(ResponseType, lst))

    @response_types.setter
    def response_types(self, value: list[ResponseType]):
        self._response_types = ";".join(map(str, value))

    @hybrid_property
    def redirect_uris(self) -> list[str]:
        lst = self._redirect_uris.split("\n")
        return lst

    @redirect_uris.setter
    def redirect_uris(self, value: list[str]):
        self._redirect_uris = "\n".join(value)

    @hybrid_method
    def verify_client_secret(self, value: str) -> bool:
        try:
            _hasher.verify(self._client_secret, value)
            if _hasher.check_needs_rehash(self._client_secret):
                self._client_secret = _hasher.hash(value)
            return True
        except Argon2Error:
            return False


class OAuth2UserPairwise(AsyncAttrs, Base):
    __tablename__ = "oauth2_user_pairwise"
    user_id: Mapped[int] = mapped_column(ForeignKey("oauth2_user.id", ondelete='CASCADE'), primary_key=True)
    sector_id: Mapped[int] = mapped_column(ForeignKey("oauth2_sector_identifier.id", ondelete='CASCADE'),
                                           primary_key=True)
    sub: Mapped[str] = mapped_column(nullable=False, unique=True, index=True)


# -*- Session definitions -*-

# Exists three types of session:
#   - OAuth2ProviderSession
#   - OAuth2UserSession
#   - OAuth2ClientSession
# OAuth2ProviderSession:
#   This session obtained direct by user via user-agent or transparent system client (acts like user-agent)
#   Provider frontend via special client_id 'frontend' call /token endpoint with login/password pair to authenticate user
#   In this case reauthentication process must be performed via 2fa (if enabled) or password without login.
#   Also, provider frontend may initial external provider authentification for obtain user information instead login/password.
#   In this case reauthentication process must be performed via the same external provider (password and 2fa not allowed)
#   For transparent system client (like mobile/native app with login/password) allowed only password grant (and 2fa)
#   Session obtained from this app can't be used as master session for other client authentication.
# OAuth2UserSession:
#   This session obtained by client via authorization endpoint by redirecting to provider frontend.
#   For such clients not exists long session flags, refresh token always has the same expiration time
#   Also for this clients may enable ip constrains
# OAuth2ClientSession:
#   This session obtained by client for itself.
#   Used for service authorization in system for request other services.
#   Can be used for revoke and introspect endpoints
#
# uid value of session is unique for all sessions (all types)

class OAuth2ProviderSession(AsyncAttrs, Base):
    """
    Provider session.
    Created if:
        - Special client_id == 'frontend', grant_type == 'password'
        - External provider authorization process (additional oauth2_external_state record created)
        - System transparent client: grant_type == 'password'
          In this case client acts as user with user scopes.
          Third-party client must not be system client
    Only two first types authentication may be as master for user session (because they embedded to provider)
    This type of session may use DPoP tokens if supported by frontend.
    You can require use of DPoP for provider sessions, but you must add support for creation DPoP tokens in frontend.
    """
    __tablename__ = 'oauth2_provider_session'
    # Generated by /oauth/token endpoint whew first session access token created (or external_client_pipeline)
    uid: Mapped[str] = mapped_column(primary_key=True)
    # Authenticated user id
    user_id: Mapped[int] = mapped_column(ForeignKey("oauth2_user.id", ondelete='CASCADE'), nullable=False)
    # Authenticated system client id
    client_id: Mapped[int] = mapped_column(ForeignKey("oauth2_client.id", ondelete="CASCADE"), nullable=True)
    # External client id
    # ForeignKey("oauth2_external_client.id", ondelete="CASCADE")
    external_client_id: Mapped[int] = mapped_column(nullable=True)
    # Control refresh token validity (only one valid refresh token per session) (for frontend exists always)
    refresh_token_jti: Mapped[str] = mapped_column(nullable=False)
    # Creation time
    started_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False,
                                                 server_default=func.current_timestamp())
    # Expire time (updated on refresh process)
    expire_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False)
    # Last time when reauthentication done (used for process max_age parameter)
    reauthenticated_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False,
                                                         server_default=func.current_timestamp())
    # Mark that need use 'long' expiration time for expire_at (long-lived session without user activity)
    long_session: Mapped[bool] = mapped_column(nullable=False, server_default="FALSE")
    # Fingerprint tell the same browser and ip (may empty if system client)
    fingerprint: Mapped[str] = mapped_column(nullable=False)
    # dpop_jkt
    dpop_jkt: Mapped[str] = mapped_column(nullable=True)
    # Space-delimited amr values. Always contains primary method reference (or amr list from external client)
    amr: Mapped[str] = mapped_column(nullable=False, server_default="")
    # list of allowed reauthenticate methods for End-User authentication. One of this must be completed.
    reauthenticate_via: Mapped[str] = mapped_column(nullable=False, server_default="")
    # Partial authenticated session, waiting for mfa complete
    mfa_waiting: Mapped[bool] = mapped_column(nullable=False, server_default="FALSE")
    # Expire time for incomplete session (if mfa not completed before this time, session closed)
    expire_mfa_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=True)


class OAuth2UserSession(AsyncAttrs, Base):
    """
    User session via client.

    ps_uid is provider session via that client obtain authentification
    If ps_uid session will be closed, any children sessions also will be closed.
    This value not setting if:
        - Requested offline refresh (offline_refresh allows session without master session)
    """
    __tablename__ = 'oauth2_user_session'
    # Generated by /oauth/token endpoint whew first session access token created (or external_client_pipeline)
    uid: Mapped[str] = mapped_column(primary_key=True)
    # Provider session uid
    ps_uid: Mapped[str] = mapped_column(ForeignKey("oauth2_provider_session.uid", ondelete='CASCADE'), nullable=True)
    # Authenticated user id
    user_id: Mapped[int] = mapped_column(ForeignKey("oauth2_user.id", ondelete='CASCADE'), nullable=False)
    # Authenticated client id
    client_id: Mapped[int] = mapped_column(ForeignKey("oauth2_client.id", ondelete="CASCADE"), nullable=False)
    # Control refresh token validity (only one valid refresh token per session) (client may be without refresh)
    refresh_token_jti: Mapped[str] = mapped_column(nullable=True)
    # Space-separated current (active) scopes. This scopes approved by user to client.
    scope: Mapped[str] = mapped_column(nullable=False)
    # OIDC claims serialized JSON if presented
    claims: Mapped[str] = mapped_column(nullable=True)
    # Creation time
    started_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False,
                                                 server_default=func.current_timestamp())
    # Expire time (updated on refresh process)
    expire_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False)
    # Last time when reauthentication done (used for process max_age parameter)
    # Clients may reauthenticate user by repeat authentication flow
    # This value not copied from provider session because we need user confirm for current client
    reauthenticated_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False,
                                                         server_default=func.current_timestamp())
    # Additional client restriction. If presented, access from wrong ip cause invalid_token error and revoke access
    access_bound_ip: Mapped[str] = mapped_column(nullable=True)
    # Additional client restriction. If presented, refresh from wrong ip cause invalid_grant error and revoke refresh
    refresh_bound_ip: Mapped[str] = mapped_column(nullable=True)
    # dpop_jkt
    dpop_jkt: Mapped[str] = mapped_column(nullable=True)
    # Space-delimited amr values (if specified). Flags for id_token about authentication methods used
    # Copied from Provider session
    amr: Mapped[str] = mapped_column(nullable=False, server_default="")


class OAuth2ClientSession(AsyncAttrs, Base):
    """
    Client session obtained via client_credential grant.
    """
    __tablename__ = 'oauth2_client_session'
    # Generated by /oauth/token endpoint whew first session access token created (or external_client_pipeline)
    uid: Mapped[str] = mapped_column(primary_key=True)
    # Authenticated client id
    client_id: Mapped[int] = mapped_column(ForeignKey("oauth2_client.id", ondelete="CASCADE"), nullable=False)
    # Control refresh token validity (only one valid refresh token per session) (client may be without refresh)
    refresh_token_jti: Mapped[str] = mapped_column(nullable=True)
    # Space-separated current (active) scopes.
    scope: Mapped[str] = mapped_column(nullable=False)
    # Creation time
    started_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False,
                                                 server_default=func.current_timestamp())
    # Expire time (updated on refresh process)
    expire_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False)
    # Additional client restriction. If presented, access from wrong ip cause invalid_token error and revoke access
    access_bound_ip: Mapped[str] = mapped_column(nullable=True)
    # Additional client restriction. If presented, refresh from wrong ip cause invalid_grant error and revoke refresh
    refresh_bound_ip: Mapped[str] = mapped_column(nullable=True)
    dpop_jkt: Mapped[str] = mapped_column(nullable=True)


class OAuth2AccessRevoked(AsyncAttrs, Base):
    """
    Table for revoked access tokens.
    """
    __tablename__ = 'oauth2_access_revoked'
    # Session uid that owned token
    uid: Mapped[str] = mapped_column(primary_key=True)
    # Access token jti value
    jti: Mapped[str] = mapped_column(primary_key=True)
    # Foreign keys to session tables (auto remove revoke records when session closed)
    p_uid: Mapped[str] = mapped_column(ForeignKey("oauth2_provider_session.uid", ondelete="CASCADE"), nullable=True)
    u_uid: Mapped[str] = mapped_column(ForeignKey("oauth2_user_session.uid", ondelete="CASCADE"), nullable=True)
    c_uid: Mapped[str] = mapped_column(ForeignKey("oauth2_client_session.uid", ondelete="CASCADE"), nullable=True)
    # Token expiration time for remove records by cleanup process
    expire_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False)


# class OAuth2ClientPreviousUsed(AsyncAttrs, Base):
#     """
#     Optional authorization code protection
#     to preventing the use of constant values for the PKCE challenge or OpenID Connect nonce.
#     """
#     __tablename__ = 'oauth2_client_previous_used'
#     client_id: Mapped[int] = mapped_column(ForeignKey("oauth2_client.id", ondelete='CASCADE'), primary_key=True)
#     code_challenge: Mapped[str] = mapped_column(nullable=True)
#     nonce: Mapped[str] = mapped_column(nullable=True)


class OAuth2Code(AsyncAttrs, Base):
    """
    Authorization code returned to client with bound information.
    """
    __tablename__ = 'oauth2_code'
    code: Mapped[str] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("oauth2_user.id", ondelete='CASCADE'), nullable=False)
    client_id: Mapped[int] = mapped_column(ForeignKey("oauth2_client.id", ondelete='CASCADE'), nullable=False)
    # Requested scopes
    scope: Mapped[str] = mapped_column(nullable=False)
    # None if default value
    redirect_uri: Mapped[str] = mapped_column(nullable=True)
    # (if PKCE enabled for request)
    code_challenge: Mapped[str] = mapped_column(nullable=True)
    # (if PKCE enabled for request)
    code_challenge_method: Mapped[str] = mapped_column(nullable=True)
    # (if it OIDC request and its present in request)
    nonce: Mapped[str] = mapped_column(nullable=True)
    # (if it OIDC request and its present in request) serialized JSON
    claims: Mapped[str] = mapped_column(nullable=True)
    dpop_jkt: Mapped[str] = mapped_column(nullable=True)
    expire_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False)


class OAuth2DeviceCode(AsyncAttrs, Base):
    """
    Authorization device code returned to client with bound information.
    """
    __tablename__ = 'oauth2_device_code'
    # Device_code will be sent by client to check status
    device_code: Mapped[str] = mapped_column(primary_key=True, unique=True)
    # User code end user send to special endpoint to authorized client
    user_code: Mapped[str] = mapped_column(primary_key=True, unique=True)
    # If client authorized, it's id will be set
    user_id: Mapped[int] = mapped_column(ForeignKey("oauth2_user.id", ondelete='CASCADE'), nullable=True)
    # Client id, who initiate process
    client_id: Mapped[int] = mapped_column(ForeignKey("oauth2_client.id", ondelete='CASCADE'), nullable=False)
    # Requested scopes
    scope: Mapped[str] = mapped_column(nullable=False)
    # If user approve code, this set to True
    # If user reject code, this set to False
    # (after pull with this state set, code will be removed)
    approved: Mapped[bool] = mapped_column(nullable=True)
    # Interval in seconds between pulls
    interval: Mapped[int] = mapped_column(nullable=False)
    last_pull: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False,
                                                server_default=func.current_timestamp())
    # When code expired
    # Code don't removed until client pull or after 30 minutes apter expiration
    expire_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False)

# class OAuth2ExternalProviders(AsyncAttrs, Base):
#     __tablename__ = 'oauth2_external_providers'
